# Generated by Django 3.1.4 on 2020-12-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField(max_length=1000)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('important', models.BooleanField(null=True)),
            ],
        ),
    ]
